# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[7.0].define(version: 2022_04_12_053735) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "examples", force: :cascade do |t|
    t.string "title"
    t.text "body"
    t.boolean "seed"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "products", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "x_division"
    t.string "x_dept_name"
    t.string "x_category"
    t.string "x_class_name"
    t.string "x_subclass"
    t.string "x_style_code"
    t.string "x_style_name"
    t.string "x_displayname"
    t.string "x_style_color"
    t.string "x_vendor_name"
    t.string "x_photo"
    t.string "x_plus_photo"
    t.string "x_color_name"
    t.string "x_fabric_name"
    t.string "x_bodyfit"
    t.string "x_detail"
    t.string "x_patternprint"
    t.string "x_collection"
    t.string "x_lifestyle"
    t.string "x_core_category"
    t.string "x_new_style_color"
    t.string "x_new_style"
    t.string "x_first_received"
    t.string "x_last_received"
    t.string "x_current_cost"
    t.string "x_sales_price"
    t.string "x_compare_at_price"
    t.string "x_original_price"
    t.string "x_imu"
    t.string "x_mmu"
    t.string "x_reg_markdown"
    t.string "x_last_markdown"
    t.string "x_shopify_visibility"
    t.string "x_avg_customer_rating"
    t.string "x_customer_reviews"
    t.string "x_customer_requests"
    t.string "x_model_name"
    t.string "x_plus_model"
    t.string "x_influencer_name"
    t.string "x_influencer_upload_date"
    t.string "x_buyer"
    t.string "x_age"
    t.string "x_qc_hold"
    t.string "x_jr_sales_units"
    t.string "x_jr_sales_units_1_wk_ago"
    t.string "x_jr_sales_units_2_wk_ago"
    t.string "x_jr_sales_units_3_wk_ago"
    t.string "x_jr_sales_units_last_4_weeks"
    t.string "x_jr_mtd_sales_units"
    t.string "x_jr_ytd_sales_units"
    t.string "x_jr_ltd_sales_units"
    t.string "x_jr_eop_units"
    t.string "x_jr_woh_units"
    t.string "x_jr_tot_oo_units"
    t.string "x_jr_tot_oo_retail"
    t.string "x_jr_tot_oo_cost"
    t.string "x_jr_tot_oo_imu"
    t.string "x_jr_next_order_due_date"
    t.string "x_jr_last_order_due_date"
    t.string "x_jr_oo_units_curr_month"
    t.string "x_jr_oo_units_next_month"
    t.string "x_jr_oo_units_in_2_months"
    t.string "x_jr_oo_units_in_3_months"
    t.string "x_jr_oo_units_in_4_months"
    t.string "x_jr_oo_units_in_5_months"
    t.string "x_jr_oo_units_in_6_months"
    t.string "x_jr_avg_daily_sales_units"
    t.string "x_jr_avg_daily_sales_units_1_ago"
    t.string "x_jr_avg_daily_sales_units_2_ago"
    t.string "x_jr_avg_daily_sales_units_3_ago"
    t.string "x_jr_sales_retail"
    t.string "x_jr_sales_retail_mtd"
    t.string "x_jr_sales_retail_ytd"
    t.string "x_jr_gm"
    t.string "x_jr_gm_mtd"
    t.string "x_jr_gm_ytd"
    t.string "x_plus_sales_units"
    t.string "x_plus_sales_units_1_wk_ago"
    t.string "x_plus_sales_units_2_wk_ago"
    t.string "x_plus_sales_units_3_wk_ago"
    t.string "x_plus_sales_units_last_4_weeks"
    t.string "x_plus_mtd_sales_units"
    t.string "x_plus_ytd_sales_units"
    t.string "x_plus_ltd_sales_units"
    t.string "x_plus_eop_units"
    t.string "x_plus_woh_units"
    t.string "x_plus_tot_oo_units"
    t.string "x_plus_tot_oo_retail"
    t.string "x_plus_tot_oo_cost"
    t.string "x_plus_tot_oo_imu"
    t.string "x_plus_next_order_due_date"
    t.string "x_plus_last_order_due_date"
    t.string "x_plus_oo_units_curr_month"
    t.string "x_plus_oo_units_next_month"
    t.string "x_plus_oo_units_in_2_months"
    t.string "x_plus_oo_units_in_3_months"
    t.string "x_plus_oo_units_in_4_months"
    t.string "x_plus_oo_units_in_5_months"
    t.string "x_plus_oo_units_in_6_months"
    t.string "x_plus_avg_daily_sales_units"
    t.string "x_plus_avg_daily_sales_units_1_ago"
    t.string "x_plus_avg_daily_sales_units_2_ago"
    t.string "x_plus_avg_daily_sales_units_3_ago"
    t.string "x_plus_sales_retail"
    t.string "x_plus_sales_retail_mtd"
    t.string "x_plus_sales_retail_ytd"
    t.string "x_plus_gm"
    t.string "x_plus_gm_mtd"
    t.string "x_plus_gm_ytd"
    t.string "x_total_sales_units"
    t.string "x_total_sales_units_1_wk_ago"
    t.string "x_total_sales_units_2_wk_ago"
    t.string "x_total_sales_units_3_wk_ago"
    t.string "x_total_sales_units_last_4_weeks"
    t.string "x_total_mtd_sales_units"
    t.string "x_total_ytd_sales_units"
    t.string "x_total_ltd_sales_units"
    t.string "x_total_eop_units"
    t.string "x_total_woh_units"
    t.string "x_total_tot_oo_units"
    t.string "x_total_tot_oo_retail"
    t.string "x_total_tot_oo_cost"
    t.string "x_total_tot_oo_imu"
    t.string "x_total_next_order_due_date"
    t.string "x_total_last_order_due_date"
    t.string "x_total_oo_units_curr_month"
    t.string "x_total_oo_units_next_month"
    t.string "x_total_oo_units_in_2_months"
    t.string "x_total_oo_units_in_3_months"
    t.string "x_total_oo_units_in_4_months"
    t.string "x_total_oo_units_in_5_months"
    t.string "x_total_oo_units_in_6_months"
    t.string "x_total_avg_daily_sales_units"
    t.string "x_total_avg_daily_sales_units_1_ago"
    t.string "x_total_avg_daily_sales_units_2_ago"
    t.string "x_total_avg_daily_sales_units_3_ago"
    t.string "x_total_sales_retail"
    t.string "x_total_sales_retail_mtd"
    t.string "x_total_sales_retail_ytd"
    t.string "x_total_gm"
    t.string "x_total_gm_mtd"
    t.string "x_total_gm_ytd"
  end

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

end
