class AddBunchOfColsToProducts < ActiveRecord::Migration[7.0]
  def change
    add_column :products, :division, :string
    add_column :products, :dept_name, :string
    add_column :products, :category, :string
    add_column :products, :class_name, :string
    add_column :products, :subclass, :string
    add_column :products, :style_code, :string
    add_column :products, :style_name, :string
    add_column :products, :displayname, :string
    add_column :products, :style_color, :string
    add_column :products, :vendor_name, :string
    add_column :products, :photo, :string
    add_column :products, :plus_photo, :string
    add_column :products, :color_name, :string
    add_column :products, :fabric_name, :string
    add_column :products, :bodyfit, :string
    add_column :products, :detail, :string
    add_column :products, :patternprint, :string
    add_column :products, :collection, :string
    add_column :products, :lifestyle, :string
    add_column :products, :core_category, :string
    add_column :products, :new_style_color, :string
    add_column :products, :new_style, :string
    add_column :products, :first_received, :string
    add_column :products, :last_received, :string
    add_column :products, :current_cost, :string
    add_column :products, :sales_price, :string
    add_column :products, :compare_at_price, :string
    add_column :products, :original_price, :string
    add_column :products, :imu, :string
    add_column :products, :mmu, :string
    add_column :products, :reg_markdown, :string
    add_column :products, :last_markdown, :string
    add_column :products, :shopify_visibility, :string
    add_column :products, :avg_customer_rating, :string
    add_column :products, :customer_reviews, :string
    add_column :products, :customer_requests, :string
    add_column :products, :model_name, :string
    add_column :products, :plus_model, :string
    add_column :products, :influencer_name, :string
    add_column :products, :influencer_upload_date, :string
    add_column :products, :buyer, :string
    add_column :products, :age, :string
    add_column :products, :qc_hold, :string
    add_column :products, :jr_sales_units, :string
    add_column :products, :jr_sales_units_1_wk_ago, :string
    add_column :products, :jr_sales_units_2_wk_ago, :string
    add_column :products, :jr_sales_units_3_wk_ago, :string
    add_column :products, :jr_sales_units_last_4_weeks, :string
    add_column :products, :jr_mtd_sales_units, :string
    add_column :products, :jr_ytd_sales_units, :string
    add_column :products, :jr_ltd_sales_units, :string
    add_column :products, :jr_eop_units, :string
    add_column :products, :jr_woh_units, :string
    add_column :products, :jr_tot_oo_units, :string
    add_column :products, :jr_tot_oo_retail, :string
    add_column :products, :jr_tot_oo_cost, :string
    add_column :products, :jr_tot_oo_imu, :string
    add_column :products, :jr_next_order_due_date, :string
    add_column :products, :jr_last_order_due_date, :string
    add_column :products, :jr_oo_units_curr_month, :string
    add_column :products, :jr_oo_units_next_month, :string
    add_column :products, :jr_oo_units_in_2_months, :string
    add_column :products, :jr_oo_units_in_3_months, :string
    add_column :products, :jr_oo_units_in_4_months, :string
    add_column :products, :jr_oo_units_in_5_months, :string
    add_column :products, :jr_oo_units_in_6_months, :string
    add_column :products, :jr_avg_daily_sales_units, :string
    add_column :products, :jr_avg_daily_sales_units_1_ago, :string
    add_column :products, :jr_avg_daily_sales_units_2_ago, :string
    add_column :products, :jr_avg_daily_sales_units_3_ago, :string
    add_column :products, :jr_sales_retail, :string
    add_column :products, :jr_sales_retail_mtd, :string
    add_column :products, :jr_sales_retail_ytd, :string
    add_column :products, :jr_gm, :string
    add_column :products, :jr_gm_mtd, :string
    add_column :products, :jr_gm_ytd, :string
    add_column :products, :plus_sales_units, :string
    add_column :products, :plus_sales_units_1_wk_ago, :string
    add_column :products, :plus_sales_units_2_wk_ago, :string
    add_column :products, :plus_sales_units_3_wk_ago, :string
    add_column :products, :plus_sales_units_last_4_weeks, :string
    add_column :products, :plus_mtd_sales_units, :string
    add_column :products, :plus_ytd_sales_units, :string
    add_column :products, :plus_ltd_sales_units, :string
    add_column :products, :plus_eop_units, :string
    add_column :products, :plus_woh_units, :string
    add_column :products, :plus_tot_oo_units, :string
    add_column :products, :plus_tot_oo_retail, :string
    add_column :products, :plus_tot_oo_cost, :string
    add_column :products, :plus_tot_oo_imu, :string
    add_column :products, :plus_next_order_due_date, :string
    add_column :products, :plus_last_order_due_date, :string
    add_column :products, :plus_oo_units_curr_month, :string
    add_column :products, :plus_oo_units_next_month, :string
    add_column :products, :plus_oo_units_in_2_months, :string
    add_column :products, :plus_oo_units_in_3_months, :string
    add_column :products, :plus_oo_units_in_4_months, :string
    add_column :products, :plus_oo_units_in_5_months, :string
    add_column :products, :plus_oo_units_in_6_months, :string
    add_column :products, :plus_avg_daily_sales_units, :string
    add_column :products, :plus_avg_daily_sales_units_1_ago, :string
    add_column :products, :plus_avg_daily_sales_units_2_ago, :string
    add_column :products, :plus_avg_daily_sales_units_3_ago, :string
    add_column :products, :plus_sales_retail, :string
    add_column :products, :plus_sales_retail_mtd, :string
    add_column :products, :plus_sales_retail_ytd, :string
    add_column :products, :plus_gm, :string
    add_column :products, :plus_gm_mtd, :string
    add_column :products, :plus_gm_ytd, :string
    add_column :products, :total_sales_units, :string
    add_column :products, :total_sales_units_1_wk_ago, :string
    add_column :products, :total_sales_units_2_wk_ago, :string
    add_column :products, :total_sales_units_3_wk_ago, :string
    add_column :products, :total_sales_units_last_4_weeks, :string
    add_column :products, :total_mtd_sales_units, :string
    add_column :products, :total_ytd_sales_units, :string
    add_column :products, :total_ltd_sales_units, :string
    add_column :products, :total_eop_units, :string
    add_column :products, :total_woh_units, :string
    add_column :products, :total_tot_oo_units, :string
    add_column :products, :total_tot_oo_retail, :string
    add_column :products, :total_tot_oo_cost, :string
    add_column :products, :total_tot_oo_imu, :string
    add_column :products, :total_next_order_due_date, :string
    add_column :products, :total_last_order_due_date, :string
    add_column :products, :total_oo_units_curr_month, :string
    add_column :products, :total_oo_units_next_month, :string
    add_column :products, :total_oo_units_in_2_months, :string
    add_column :products, :total_oo_units_in_3_months, :string
    add_column :products, :total_oo_units_in_4_months, :string
    add_column :products, :total_oo_units_in_5_months, :string
    add_column :products, :total_oo_units_in_6_months, :string
    add_column :products, :total_avg_daily_sales_units, :string
    add_column :products, :total_avg_daily_sales_units_1_ago, :string
    add_column :products, :total_avg_daily_sales_units_2_ago, :string
    add_column :products, :total_avg_daily_sales_units_3_ago, :string
    add_column :products, :total_sales_retail, :string
    add_column :products, :total_sales_retail_mtd, :string
    add_column :products, :total_sales_retail_ytd, :string
    add_column :products, :total_gm, :string
    add_column :products, :total_gm_mtd, :string
    add_column :products, :total_gm_ytd, :string
  end
end
