class AddBunchOfColsToProducts < ActiveRecord::Migration[7.0]
  def change
    add_column :products, :x_division, :string
    add_column :products, :x_dept_name, :string
    add_column :products, :x_category, :string
    add_column :products, :x_class_name, :string
    add_column :products, :x_subclass, :string
    add_column :products, :x_style_code, :string
    add_column :products, :x_style_name, :string
    add_column :products, :x_displayname, :string
    add_column :products, :x_style_color, :string
    add_column :products, :x_vendor_name, :string
    add_column :products, :x_photo, :string
    add_column :products, :x_plus_photo, :string
    add_column :products, :x_color_name, :string
    add_column :products, :x_fabric_name, :string
    add_column :products, :x_bodyfit, :string
    add_column :products, :x_detail, :string
    add_column :products, :x_patternprint, :string
    add_column :products, :x_collection, :string
    add_column :products, :x_lifestyle, :string
    add_column :products, :x_core_category, :string
    add_column :products, :x_new_style_color, :string
    add_column :products, :x_new_style, :string
    add_column :products, :x_first_received, :string
    add_column :products, :x_last_received, :string
    add_column :products, :x_current_cost, :string
    add_column :products, :x_sales_price, :string
    add_column :products, :x_compare_at_price, :string
    add_column :products, :x_original_price, :string
    add_column :products, :x_imu, :string
    add_column :products, :x_mmu, :string
    add_column :products, :x_reg_markdown, :string
    add_column :products, :x_last_markdown, :string
    add_column :products, :x_shopify_visibility, :string
    add_column :products, :x_avg_customer_rating, :string
    add_column :products, :x_customer_reviews, :string
    add_column :products, :x_customer_requests, :string
    add_column :products, :x_model_name, :string
    add_column :products, :x_plus_model, :string
    add_column :products, :x_influencer_name, :string
    add_column :products, :x_influencer_upload_date, :string
    add_column :products, :x_buyer, :string
    add_column :products, :x_age, :string
    add_column :products, :x_qc_hold, :string
    add_column :products, :x_jr_sales_units, :string
    add_column :products, :x_jr_sales_units_1_wk_ago, :string
    add_column :products, :x_jr_sales_units_2_wk_ago, :string
    add_column :products, :x_jr_sales_units_3_wk_ago, :string
    add_column :products, :x_jr_sales_units_last_4_weeks, :string
    add_column :products, :x_jr_mtd_sales_units, :string
    add_column :products, :x_jr_ytd_sales_units, :string
    add_column :products, :x_jr_ltd_sales_units, :string
    add_column :products, :x_jr_eop_units, :string
    add_column :products, :x_jr_woh_units, :string
    add_column :products, :x_jr_tot_oo_units, :string
    add_column :products, :x_jr_tot_oo_retail, :string
    add_column :products, :x_jr_tot_oo_cost, :string
    add_column :products, :x_jr_tot_oo_imu, :string
    add_column :products, :x_jr_next_order_due_date, :string
    add_column :products, :x_jr_last_order_due_date, :string
    add_column :products, :x_jr_oo_units_curr_month, :string
    add_column :products, :x_jr_oo_units_next_month, :string
    add_column :products, :x_jr_oo_units_in_2_months, :string
    add_column :products, :x_jr_oo_units_in_3_months, :string
    add_column :products, :x_jr_oo_units_in_4_months, :string
    add_column :products, :x_jr_oo_units_in_5_months, :string
    add_column :products, :x_jr_oo_units_in_6_months, :string
    add_column :products, :x_jr_avg_daily_sales_units, :string
    add_column :products, :x_jr_avg_daily_sales_units_1_ago, :string
    add_column :products, :x_jr_avg_daily_sales_units_2_ago, :string
    add_column :products, :x_jr_avg_daily_sales_units_3_ago, :string
    add_column :products, :x_jr_sales_retail, :string
    add_column :products, :x_jr_sales_retail_mtd, :string
    add_column :products, :x_jr_sales_retail_ytd, :string
    add_column :products, :x_jr_gm, :string
    add_column :products, :x_jr_gm_mtd, :string
    add_column :products, :x_jr_gm_ytd, :string
    add_column :products, :x_plus_sales_units, :string
    add_column :products, :x_plus_sales_units_1_wk_ago, :string
    add_column :products, :x_plus_sales_units_2_wk_ago, :string
    add_column :products, :x_plus_sales_units_3_wk_ago, :string
    add_column :products, :x_plus_sales_units_last_4_weeks, :string
    add_column :products, :x_plus_mtd_sales_units, :string
    add_column :products, :x_plus_ytd_sales_units, :string
    add_column :products, :x_plus_ltd_sales_units, :string
    add_column :products, :x_plus_eop_units, :string
    add_column :products, :x_plus_woh_units, :string
    add_column :products, :x_plus_tot_oo_units, :string
    add_column :products, :x_plus_tot_oo_retail, :string
    add_column :products, :x_plus_tot_oo_cost, :string
    add_column :products, :x_plus_tot_oo_imu, :string
    add_column :products, :x_plus_next_order_due_date, :string
    add_column :products, :x_plus_last_order_due_date, :string
    add_column :products, :x_plus_oo_units_curr_month, :string
    add_column :products, :x_plus_oo_units_next_month, :string
    add_column :products, :x_plus_oo_units_in_2_months, :string
    add_column :products, :x_plus_oo_units_in_3_months, :string
    add_column :products, :x_plus_oo_units_in_4_months, :string
    add_column :products, :x_plus_oo_units_in_5_months, :string
    add_column :products, :x_plus_oo_units_in_6_months, :string
    add_column :products, :x_plus_avg_daily_sales_units, :string
    add_column :products, :x_plus_avg_daily_sales_units_1_ago, :string
    add_column :products, :x_plus_avg_daily_sales_units_2_ago, :string
    add_column :products, :x_plus_avg_daily_sales_units_3_ago, :string
    add_column :products, :x_plus_sales_retail, :string
    add_column :products, :x_plus_sales_retail_mtd, :string
    add_column :products, :x_plus_sales_retail_ytd, :string
    add_column :products, :x_plus_gm, :string
    add_column :products, :x_plus_gm_mtd, :string
    add_column :products, :x_plus_gm_ytd, :string
    add_column :products, :x_total_sales_units, :string
    add_column :products, :x_total_sales_units_1_wk_ago, :string
    add_column :products, :x_total_sales_units_2_wk_ago, :string
    add_column :products, :x_total_sales_units_3_wk_ago, :string
    add_column :products, :x_total_sales_units_last_4_weeks, :string
    add_column :products, :x_total_mtd_sales_units, :string
    add_column :products, :x_total_ytd_sales_units, :string
    add_column :products, :x_total_ltd_sales_units, :string
    add_column :products, :x_total_eop_units, :string
    add_column :products, :x_total_woh_units, :string
    add_column :products, :x_total_tot_oo_units, :string
    add_column :products, :x_total_tot_oo_retail, :string
    add_column :products, :x_total_tot_oo_cost, :string
    add_column :products, :x_total_tot_oo_imu, :string
    add_column :products, :x_total_next_order_due_date, :string
    add_column :products, :x_total_last_order_due_date, :string
    add_column :products, :x_total_oo_units_curr_month, :string
    add_column :products, :x_total_oo_units_next_month, :string
    add_column :products, :x_total_oo_units_in_2_months, :string
    add_column :products, :x_total_oo_units_in_3_months, :string
    add_column :products, :x_total_oo_units_in_4_months, :string
    add_column :products, :x_total_oo_units_in_5_months, :string
    add_column :products, :x_total_oo_units_in_6_months, :string
    add_column :products, :x_total_avg_daily_sales_units, :string
    add_column :products, :x_total_avg_daily_sales_units_1_ago, :string
    add_column :products, :x_total_avg_daily_sales_units_2_ago, :string
    add_column :products, :x_total_avg_daily_sales_units_3_ago, :string
    add_column :products, :x_total_sales_retail, :string
    add_column :products, :x_total_sales_retail_mtd, :string
    add_column :products, :x_total_sales_retail_ytd, :string
    add_column :products, :x_total_gm, :string
    add_column :products, :x_total_gm_mtd, :string
    add_column :products, :x_total_gm_ytd, :string
  end
end
